src/mysite/accounts/urls.py
#適宜プロジェクトごとに追加するファイル
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include

app_name = 'accounts'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('registration/', views.Registration.as_view(), name='registration'),
    path('registration/temporary', views.TemporaryRegistration.as_view(), name='temporary_registration'),
    path('registration/complete/<token>/', views.RegistrationComplete.as_view(), name='complete_registration'),
]

src/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( '', include('grandmenu_spa.urls')),
    path('accounts/', include('accounts.urls')),  #accounts追加
]

src/mysite/accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, BaseUserManager, AbstractBaseUser
from django.db.models.fields import BLANK_CHOICE_DASH, BooleanField
from django.utils import timezone
from django.utils.timezone import localtime


class StoreUserManager(BaseUserManager):
    '''createuser/createsuperuser時に作成するモデル設定クラス'''

    def create_user(self, email, password=None):
        '''createuser'''
        if not email:
            raise ValueError("Enter Email!! (Eメールを入力してください)")
        storeuser = self.model(
            email=email
        )
        storeuser.set_password(password)
        storeuser.is_active = True   # コンソールから作成した場合は本登録まで完了
        storeuser.save(using=self._db)

    def create_superuser(self, email, password=None):
        '''createsuperuser'''
        storeuser = self.model(
            email=email
        )
        storeuser.set_password(password)
        storeuser.is_staff = True
        storeuser.is_active = True
        storeuser.is_superuser = True
        storeuser.save(using=self._db)

        return storeuser





class Store(AbstractBaseUser, PermissionsMixin):
    '''店舗情報管理クラス'''
    email = models.EmailField(max_length=255, unique=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    # 以下カスタム追加レコード
    store_name = models.CharField(max_length=100)
    store_url = models.CharField(max_length=255)
    store_telnum = models.IntegerField(null=True, verbose_name='電話番号')
    store_postal_code = models.CharField(max_length=8, null=True)
    store_address1 = models.CharField(max_length=100)
    store_address2 = models.CharField(max_length=100)
    store_address3 = models.CharField(max_length=100)
    store_address4 = models.CharField(max_length=100)
    store_address5 = models.CharField(null=True, max_length=100)
    store_kind = models.CharField(max_length=50)
    seating_capacity = models.IntegerField(default=1)
    takeout_support = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'        # このテーブルのレコードを一意に識別
    # REQUIRED_FIELDS = ['username']  # スーパーユーザー作成時に必要 (emailとパスワードは必須なのでそれ以外を指定)

    objects = StoreUserManager()

    def email_user(self, subject, message, from_email=None, **kwargs):
        """仮登録ユーザーへのEメール 送信"""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = '店舗情報'
        verbose_name_plural = '店舗情報'

    def __str__(self):
        return self.email

src/mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm


Store = get_user_model()

class UserCreationForm(forms.ModelForm):
    '''Storeを作成する際のform情報'''
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='password (確認用)', widget=forms.PasswordInput)

    class Meta:
        model = Store
        fields = ('store_name', 'email', 'password')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise ValidationError('パスワードが一致しません')

    def save(self, commit=False):
        storeuser = super().save(commit=False)
        storeuser.set_password(self.cleaned_data.get('password'))
        storeuser.save()
        return storeuser

class UserChangeForm(forms.ModelForm):
    '''Storeを編集する際のform情報'''
    password = ReadOnlyPasswordHashField()
    store_url = forms.CharField(required=False, label='ストアコード(ここはまだ形式未定)')
    store_telnum = forms.IntegerField(required=False, label='電話番号')
    store_postal_code = forms.IntegerField(required=False, label='郵便番号')
    store_address1 = forms.CharField(required=False, label='住所１')
    store_address2 = forms.CharField(required=False, label='住所２')
    store_address3 = forms.CharField(required=False, label='住所３')
    store_address4 = forms.CharField(required=False, label='住所４')
    store_address5 = forms.CharField(required=False, label='住所5')
    store_name = forms.CharField(required=False, label='店名')
    store_kind = forms.CharField(required=False, label='店種別')
    seating_capacity = forms.IntegerField(required=False, label='席数')
    takeout_support = forms.BooleanField(required=False, label='テイクアウト有無')


    class Meta:
        model = Store
        fields = '__all__'
        # fields = ('email', 'store_url', 'store_postal_code', 'is_staff', 'is_active', 'is_superuser', 'store_address1', 'store_address2', 'store_address3', 'store_address4', 'store_kind', 'seating_capacity', 'takeout_support')

    '''admin画面に非表示にしているためとりあえず必要なし'''
    # def clean_password(self):
    #     # すでに登録されているパスワードを返す(変更できないように)
    #     return self.initial['password']

class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] ='text_box'
        self.fields['username'].widget.attrs['placeholder'] ='登録メールアドレス'
        self.fields['password'].widget.attrs['class'] ='text_box'
        self.fields['password'].widget.attrs['placeholder'] ='パスワード'

class UserRegistrationForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = Store
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] ='text_box'
        self.fields['email'].widget.attrs['placeholder'] ='登録メールアドレス'
        self.fields['password'].widget.attrs['class'] ='text_box'
        self.fields['password'].widget.attrs['placeholder'] ='パスワード'
        self.fields['confirm_password'].widget.attrs['class'] ='text_box'
        self.fields['confirm_password'].widget.attrs['placeholder'] ='パスワード(確認用)'

        # for field in self.fields.values():
        #     field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        Store.objects.filter(email=email, is_active=False).delete()
        return email

src/mysite/accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.views import generic
from .forms import (
    LoginForm, UserRegistrationForm
)
from .models import Store
import random, string

User = get_user_model()


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LogoutView):
    """ログアウトページ"""
    pass

class Registration(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'accounts/registration.html'
    form_class = UserRegistrationForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使う。
        # 退会処理も、is_activeをFalseにするだけ。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('accounts/mail_template/create/subject.txt', context)
        message = render_to_string('accounts/mail_template/create/message.txt', context)
        user.email_user(subject, message)
        return redirect('accounts:temporary_registration')


class TemporaryRegistration(generic.TemplateView):
    """ユーザー仮登録"""
    template_name = 'accounts/temporary_registration.html'


class RegistrationComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'accounts/complete_registration.html'
    # ここのアクセス時間についてはいつか検証しておく。本当に1hで無効になる？
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    store = Store.objects.get(pk=user_pk)
                    store.store_url = MakeStrRandomCode(24) # とりあえず適当に24文字作成
                    store.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()



'''
    store_url用にランダムの文字列を作成する関数
'''
def MakeStrRandomCode(length):
   randomlist = [random.choice(string.ascii_letters + string.digits) for i in range(length)]
   return ''.join(randomlist)

src/mysite/templates/accounts/complete_registration.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login Form</title>
    <link rel="stylesheet" href="{% static 'style/HTML5 Doctor CSS Reset.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
    <header>
        <h1>
            GroundMenu
        </h1>
    </header>
    <div class="wrapper--h-center_v-center">
    <p>
        本登録が完了しました。<br>
        登録されたメールアドレスとパスワードでログインしてください。<br>
        <button class="submit_button">
            <a class="link--secondary" href="{% url 'accounts:login' %}">ログインへ</a>
        </button>
        
    </p>
    </div>
    
</body>
</html>

src/mysite/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login Form</title>

    <link rel="stylesheet" href="{% static 'style/HTML5 Doctor CSS Reset.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
    <header>
        <h1>
            GroundMenu
        </h1>
    </header>
    <div class="wrapper--h-center_v-center">
        <form class="form" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <h2>ログイン</h2>
            <h4>メールアドレス</h4>
            <!-- <input type="email" name="email" class="text_box" placeholder="メールアドレス"> -->
            {{ form.username }}
            <h4>パスワード</h4>
            <!-- ><input type="password" name="password" class="text_box" placeholder="パスワード">-->
            {{ form.password }}
            {% if form.errors %}
            {{ form.non_field_errors }}
            {% endif %}
            <button type="submit" name="" value="login.html" class="submit_button">ログイン</button>
        </form>
    <a class="link--secondary" href="{% url 'accounts:registration' %}">新規登録へ</a>
    </div>
    
</body>
</html>

src/mysite/templates/accounts/registration.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login Form</title>
    <link rel="stylesheet" href="{% static 'style/HTML5 Doctor CSS Reset.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
    <header>
        <h1>
            GroundMenu
        </h1>
    </header>
    <div class="wrapper--h-center_v-center">
        <form class="form" action="" method="post">
            {% csrf_token %}
            <h2>新規登録</h2>
            <h4>メールアドレス</h4>
            <!-- <input type="email" name="email" class="text_box" placeholder="メールアドレス"> -->
            {{ form.email }}
            <div class="error">{{ form.email.errors }}</div>
            <h4>パスワード</h4>
            <!-- <input type="password" name="password" class="text_box" placeholder="パスワード"> -->
            {{ form.password }}
            <h4>パスワード再入力</h4>
            <!-- <input type="password" name="repassword" class="text_box" placeholder="パスワード再入力"> -->
            {{ form.confirm_password }}
            {% if form.errors %}
            {{ form.non_field_errors }}
            {% endif %}
            <button type="submit" name="" value="login" class="submit_button">新規登録</button>
        </form>
    <a class="link--secondary" href="{% url 'accounts:login' %}">ログインへ</a>
    </div>
    
</body>
</html>

src/mysite/templates/accounts/temporary_registration.html
<!DOCTYPE html>
{% load static %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login Form</title>
    <link rel="stylesheet" href="{% static 'style/HTML5 Doctor CSS Reset.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
    <header>
        <h1>
            GroundMenu
        </h1>
    </header>
    <div class="wrapper--h-center_v-center">
    <p>
        会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
        確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。<br>
    </p>
    </div>
    
</body>
</html>